### ISSUE TITLE
Inconsistency between Chart.yaml in repo and in the article

### ISSUE THREAD

**Issue by wawrzek** [arthurk/argocd-example-install#2]
@arthurk In the code snipped (content of Chart.yaml) the version is set to 2.11.0. In the repo it is 4.2.2. Later in text, the correct version is mentioned in context of the tar.gz downloaded.

 The latest is 4.9.10, but that's OK, the latest version is usually a moving target. What might be handy is point to readers how to check the latest version of the chart.

**Comment by arthurk** [comment]
thanks, I'll update the article with the latest chart version and also fix the chart.yaml

**Comment by aliwo** [comment]
Thanks for the great article :) any updates?

**Comment by arthurk** [comment]
I've updated the inconsistency. As for version update I'll wait for the 2.6 release to update everything since the web ui has changed a bit and I need to update all screenshots too
